ТЗ-13
Rolik8797/java-shareit pull request #1
Opened 2023-09-16 16:46 UTC by Rolik8797

2023-09-16 16:50 UTC, Rolik8797 commented
ТЗ-13

2023-09-17 21:06 UTC, NikolaiDem requested changes

2023-09-17 21:06 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +public class ItemController {
Лучше логировать все входящие запросы.
Аналогично для остальных контроллеров

2023-09-17 21:06 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        return ResponseEntity.status(201).body(itemCreated);
Как альтернатива вместо конструирования ResponseEntity со статусом можно статус задать аннотацией на методе, а из метода вернуть сам объект без обертки. Например,

    @PatchMapping("/{itemId}")
    @ResponseStatus(HttpStatus.CREATED)
    public ItemDto updateItem(@RequestBody ItemDto itemDto, @PathVariable Long itemId, @RequestHeader(userIdHeader) Long userId) {
        return itemService.updateItem(itemDto, itemId, userId);
    }

Аналогично для остальных методов и контроллеров.

2023-09-17 21:06 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        itemIdValidator(item);
Если item был записан в БД корректно, то для чего нужна проверка после чтения из БД?

2023-09-17 21:06 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        return itemStorage.getAllItems()
Если в БД будет 1 000 000 000 item-ов, то выгружать их в память каждый раз неэффективно. Нужно сделать так, чтобы itemStorage вернул сразу только item-ы запрошенного юзера.
АНалогично для метода searchItemsByDescription

2023-09-17 21:06 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (itemDto.getName() != null) {
Строки 101-109 - это уже не валидация, тем более они дублируют метод updateItemFields

2023-09-17 21:06 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        itemIdValidator(item);
Для чего валидация при удалении?

2023-09-17 21:06 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private ItemDto itemToItemDto(Item item) {
Методы itemToItemDto и itemDtoToItem должны находиться в соответствующем классе ItemMapper

2023-09-17 21:06 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (!userStorage.getAll().contains(userStorage.get(userId))) {
if (userStorage.get(userId) == null) {
            throw new NotFoundException(String.format("User with id = %d not found.", userId));
        }

2023-09-17 21:06 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    private UserDto userToDto(User user) {
Методы userToDto и dtoToUser должны быть в классе UserMapper

2023-09-17 21:06 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        User user = userStorage.get(id);
А вообще предполагается, что  userStorage.get(id) когда-нибудь вернет null? В текущей реализации userStorage такого не наблюдается

2023-09-17 21:06 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/storage/UserStorageImpl.java
> +        if (user.getName() != null && !user.getName().isEmpty()) {
Логика на строках 42-47 должна быть в сервисе

2023-09-18 06:02 UTC, Rolik8797 commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +public class ItemController {
поправила

2023-09-18 06:19 UTC, Rolik8797 commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        return ResponseEntity.status(201).body(itemCreated);
поправила

2023-09-18 06:33 UTC, Rolik8797 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private ItemDto itemToItemDto(Item item) {
поправила

2023-09-18 06:38 UTC, Rolik8797 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        itemIdValidator(item);
убрала

2023-09-18 07:15 UTC, Rolik8797 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        return itemStorage.getAllItems()
поправила

2023-09-18 07:21 UTC, Rolik8797 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (itemDto.getName() != null) {
убрала

2023-09-18 07:23 UTC, Rolik8797 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        itemIdValidator(item);
поправила

2023-09-18 07:24 UTC, Rolik8797 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (!userStorage.getAll().contains(userStorage.get(userId))) {
исправила

2023-09-18 07:31 UTC, Rolik8797 commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    private UserDto userToDto(User user) {
перенесла

2023-09-18 07:38 UTC, Rolik8797 commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        User user = userStorage.get(id);
поправила

2023-09-18 09:13 UTC, Rolik8797 commented on src/main/java/ru/practicum/shareit/user/storage/UserStorageImpl.java
> +        if (user.getName() != null && !user.getName().isEmpty()) {
перенесла

2023-09-18 09:19 UTC, Rolik8797 commented
ТЗ-13.2

2023-09-19 09:30 UTC, NikolaiDem approved these changes

2023-09-19 09:30 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private void itemOwnerNameDescAvailValidator(ItemDto itemDto, Item oldItem, long userId) {
itemDto не используется

2023-09-19 14:55 UTC, Rolik8797 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private void itemOwnerNameDescAvailValidator(ItemDto itemDto, Item oldItem, long userId) {
поправила

2023-10-09 05:41 UTC, merged