ТЗ16
Rolik8797/java-shareit pull request #16
Opened 2023-11-04 17:31 UTC by Rolik8797

2023-11-04 17:37 UTC, Rolik8797 commented
ТЗ16

2023-11-05 15:09 UTC, NikolaiDem requested changes

2023-11-05 15:09 UTC, NikolaiDem commented on gateway/src/main/java/ru/practicum/shareit/item/ItemExtendedDto.java
> +@Data
Лучше не использовать вместе аннотации, по которым генерятся одинаковые структуры (в данном случае конструкторы), чтобы не возникало потенциальных конфликтов. Поэтому, если нужен билдер, то вместо @Data можно отдельно вытащить геттеры, сеттеры и что еще необходимо.
Аналогично для остальных классов

2023-11-05 15:09 UTC, NikolaiDem commented on server/pom.xml
> +        <dependency>
В модуле server валидация не нужна

2023-11-05 15:09 UTC, NikolaiDem commented on server/src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +        log.error(exception.toString());
ЧТобы в логах оставался стектрейс, лучше использовать такой метод
        log.error(exception.getMessage(), exception);
Аналогично для остальных исключений

2023-11-05 15:09 UTC, NikolaiDem commented on server/src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@Data
Почему Data вместо @Getter
@Setter
@ToString 
Аналогично для остальных моделей?

2023-11-05 15:09 UTC, NikolaiDem commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> -public class BookingControllerTest {
Удалять тесты не нужно. Если все тесты на валидацию, то перенести их в модуль gateway

2023-11-06 09:11 UTC, Rolik8797 commented on gateway/src/main/java/ru/practicum/shareit/item/ItemExtendedDto.java
> +@Data
поправила

2023-11-06 09:14 UTC, Rolik8797 commented on server/src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +        log.error(exception.toString());
поменяла

2023-11-06 09:15 UTC, Rolik8797 commented on server/src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@Data
исправила

2023-11-06 12:20 UTC, Rolik8797 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> -public class BookingControllerTest {
вернула

2023-11-06 17:48 UTC, Rolik8797 commented on server/pom.xml
> +        <dependency>
???????? Очень она там нужна.

2023-11-06 17:49 UTC, Rolik8797 commented
ТЗ-16.3

2023-11-07 17:35 UTC, NikolaiDem commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> -public class BookingControllerTest {
Не все

2023-11-07 17:36 UTC, NikolaiDem commented on server/pom.xml
> +        <dependency>
Не исправлено, валидация только для gateway нужна

2023-11-07 17:37 UTC, NikolaiDem requested changes
Предыдущие замечания не исправлены

2023-11-07 21:01 UTC, Rolik8797 commented on server/pom.xml
> +        <dependency>
убрала валидацию

2023-11-07 21:01 UTC, Rolik8797 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> -public class BookingControllerTest {
добавила еще тестов

2023-11-07 21:01 UTC, Rolik8797 commented
ТЗ16-4

2023-11-07 23:02 UTC, NikolaiDem approved these changes

2023-11-10 08:43 UTC, merged