Add bookings
Rolik8797/java-shareit pull request #2
Opened 2023-10-08 22:38 UTC by Rolik8797

2023-10-09 05:44 UTC, Rolik8797 commented
ТЗ-14

2023-10-10 00:45 UTC, NikolaiDem requested changes

2023-10-10 00:45 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +package ru.practicum.shareit.booking.controller;
Переносить в отдельные пакеты не нужно.
Аналогично для остальных модулей

2023-10-10 00:45 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    private final String host = "localhost";
Все настройки необходимо задавать в application.properties.
Аналогично для остальных контроллеров

2023-10-10 00:45 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        UriComponents uriComponents = UriComponentsBuilder.newInstance()
Вынести общую часть в отдельный метод

2023-10-10 00:45 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (booking.getStatus().equals(Status.APPROVED)) {
А если статус Rejected?

2023-10-10 00:45 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                        Status.WAITING, sort);
Переносы лишние

2023-10-10 00:45 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    @Transactional
Лучше определить на уровне класса

2023-10-10 00:45 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    private void validateAddBooking(long bookerId, Booking booking, Item item) {
Лучше и проверить, что новое бронирование не будет пересекаться с уже существующими

2023-10-10 00:45 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/mapper/CommentMapper.java
> +        return modelMapper.map(comment, CommentDto.class);
Почему разные мапперы : где-то mapstruct, где-то nodelMapper?

2023-10-10 00:45 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    @Query(value = "select i from Item i where lower(i.name) like %:text% or lower(i.description) like %:text% " +
Что будет выполняться сначала or или and?

2023-10-10 00:45 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    @Transactional
Лучше вынести на уровень класса

2023-10-10 00:45 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        List<Booking> bookings = bookingRepository.findAllByItemIdAndBookerIdAndStatus(itemId, userId, Status.APPROVED,
Необходимо проверить, что бронирование было подтверждено

2023-10-10 00:45 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                .filter(booking -> booking.getItem().getId() == itemDto.getId() &&
Вместо сравнения booking.getItem().getId() == itemDto.getId() лучше использовать мапу, где ключ - itemId, а значение - список всех бронирований. Эту мапу следует использовать в вызывающем методе, чтобы в текущий метод не передавать абсолютно все бронирования, а только принадлежащие предмету.
Аналогично для комментариев

2023-10-10 00:45 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +            Logger.logSave(HttpMethod.POST, uriComponents.toUriString(), userSaved.toString());
Эти логи больше подходят для контроллера. Сервис вовсе не знает ни о каких http запросах

2023-10-10 05:50 UTC, Rolik8797 commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +package ru.practicum.shareit.booking.controller;
поправила

2023-10-10 06:57 UTC, Rolik8797 commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        UriComponents uriComponents = UriComponentsBuilder.newInstance()
поправила

2023-10-10 08:19 UTC, Rolik8797 commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    private final String host = "localhost";
изменила

2023-10-10 08:23 UTC, Rolik8797 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (booking.getStatus().equals(Status.APPROVED)) {
исправила

2023-10-10 08:28 UTC, Rolik8797 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                        Status.WAITING, sort);
убрала

2023-10-10 08:34 UTC, Rolik8797 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    @Transactional
определила

2023-10-10 08:52 UTC, Rolik8797 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    private void validateAddBooking(long bookerId, Booking booking, Item item) {
добавила проверку

2023-10-10 09:30 UTC, Rolik8797 commented on src/main/java/ru/practicum/shareit/item/mapper/CommentMapper.java
> +        return modelMapper.map(comment, CommentDto.class);
поправила

2023-10-10 09:36 UTC, Rolik8797 commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    @Query(value = "select i from Item i where lower(i.name) like %:text% or lower(i.description) like %:text% " +
Сначала будут выполнены операции like с использованием or, что означает, что будет выполняться поиск элементов, у которых name или description содержат указанный текст (:text). Затем, после этой операции, будет добавлено условие and i.available=true для фильтрации только доступных элементов из результатов, найденных по предыдущему условию like с оператором or.

2023-10-10 09:40 UTC, Rolik8797 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    @Transactional
вынесла

2023-10-10 09:48 UTC, Rolik8797 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        List<Booking> bookings = bookingRepository.findAllByItemIdAndBookerIdAndStatus(itemId, userId, Status.APPROVED,
добавила проверку

2023-10-10 11:34 UTC, Rolik8797 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                .filter(booking -> booking.getItem().getId() == itemDto.getId() &&
поправила

2023-10-10 11:58 UTC, Rolik8797 commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +            Logger.logSave(HttpMethod.POST, uriComponents.toUriString(), userSaved.toString());
убрала

2023-10-10 12:08 UTC, Rolik8797 commented
ТЗ14-2

2023-10-11 12:01 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    @Query(value = "select i from Item i where lower(i.name) like %:text% or lower(i.description) like %:text% " +
Все абсолютно наоборот)

2023-10-11 12:02 UTC, NikolaiDem approved these changes

2023-10-13 11:59 UTC, merged