ТЗ15
Rolik8797/java-shareit pull request #6
Opened 2023-10-15 07:46 UTC by Rolik8797

2023-10-16 05:32 UTC, NikolaiDem requested changes
Необходимо добавить юнит тесты для классов сервисов

2023-10-16 05:32 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
>  @Data
Лучше не использовать вместе аннотации, по которым генерятся одинаковые структуры (в данном случае конструкторы), чтобы не возникало потенциальных конфликтов. Поэтому, если нужен билдер, то вместо @Data можно отдельно вытащить геттеры, сеттеры и что еще необходимо.
Аналогично для остальных классов

2023-10-16 05:32 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    @Query("SELECT i.id FROM Item AS i " +
Запрос можно упростить до SELECT i.id FROM Item i WHERE i.owner.id = ?1

2023-10-16 05:32 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    List<Item> findAllByNameOrDescriptionContainingIgnoreCaseAndAvailableTrue(Pageable pageable,
Запрос будет выполняться как 
cond1 or (cond2 && cond3), что неверно

2023-10-16 05:32 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    private final ItemRepository items;
Почему удалены все repository?

2023-10-16 05:32 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            item.setLastBooking(mapper.mapToBookingShortDto(bookings.findFirstByItemIdAndStartBeforeAndStatusOrderByEndDesc(
Проблема N+1 запроса

2023-10-16 05:32 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            item.setNextBooking(mapper.mapToBookingShortDto(bookings
Проблема N+1 запроса

2023-10-16 05:32 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Set<Comment> comments;
Проблема N+1 запроса, комментарии необходимо получать отдельно для всех item-ов сразу по аналогии с last и next booking-ами

2023-10-16 05:32 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +    @OneToMany(mappedBy = "request", fetch = FetchType.EAGER, cascade = CascadeType.ALL)
Проблема N+1 запроса. item-ы необходимо получить одним запросом сразу для всего списка itemRequest-ов

2023-10-16 05:32 UTC, NikolaiDem commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +@AutoConfigureMockMvc
WebMvcTest уже включает в себя AutoConfigureMockMvc, можно удалить.
Аналогично для остальных контроллеров

2023-10-16 05:32 UTC, NikolaiDem commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTest.java
> +@AutoConfigureTestDatabase
Аннотация лишняя.
Аналогично для остальных интеграционных тестов

2023-10-16 05:32 UTC, NikolaiDem commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    public void createBookingWithIncorrectBookerId() {
Хорошим паттерном написания тестов является AAA
https://freecontent.manning.com/making-better-unit-tests-part-1-the-aaa-pattern/
Замечание здесь к тому, чтобы визуально разделить 3 этих части (отделить пустыми строками).
Применить такой подход во всех тестах

2023-10-16 09:06 UTC, Rolik8797 commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
>  @Data
заменила

2023-10-16 09:10 UTC, Rolik8797 commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    @Query("SELECT i.id FROM Item AS i " +
поменяла

2023-10-16 10:23 UTC, Rolik8797 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    private final ItemRepository items;
они все на месте:   private final ItemRepository items;
    private final UserRepository users;
    private final BookingRepository bookings;
    private final CommentRepository comments;
    private final ItemMapper mapper;
    private final ItemRequestRepository itemRequests;

2023-10-16 10:45 UTC, Rolik8797 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            item.setLastBooking(mapper.mapToBookingShortDto(bookings.findFirstByItemIdAndStartBeforeAndStatusOrderByEndDesc(
поправила

2023-10-16 10:48 UTC, Rolik8797 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            item.setNextBooking(mapper.mapToBookingShortDto(bookings
поправила

2023-10-16 11:04 UTC, Rolik8797 commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Set<Comment> comments;
поправила

2023-10-16 11:58 UTC, Rolik8797 commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +    @OneToMany(mappedBy = "request", fetch = FetchType.EAGER, cascade = CascadeType.ALL)
поправила

2023-10-16 12:01 UTC, Rolik8797 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +@AutoConfigureMockMvc
удалила

2023-10-16 12:09 UTC, Rolik8797 commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTest.java
> +@AutoConfigureTestDatabase
убрала

2023-10-16 13:11 UTC, Rolik8797 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    public void createBookingWithIncorrectBookerId() {
разделила

2023-10-16 15:05 UTC, Rolik8797 commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    List<Item> findAllByNameOrDescriptionContainingIgnoreCaseAndAvailableTrue(Pageable pageable,
"найти элементы, где либо имя совпадает с заданным значением, либо описание содержит заданное значение, и при этом available равно `true".

Если обозначим условия следующим образом:

cond1 = name совпадает с заданным значением
cond2 = description содержит заданное значение
cond3 = available равно true
Тогда запрос будет выполняться как cond1 or (cond2 and cond3). Это означает, что он вернет элементы, для которых хотя бы одно из следующих условий верно:

Имя совпадает с заданным значением (cond1 истинно)
Описание содержит заданное значение и при этом available равно true (cond2 и cond3 истинны).???

2023-10-16 15:14 UTC, Rolik8797 commented
15-2

2023-10-17 14:03 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    List<Item> findAllByNameOrDescriptionContainingIgnoreCaseAndAvailableTrue(Pageable pageable,
AND имеет приоритет выше OR

2023-10-17 14:03 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    private final ItemRepository items;
имел ввиду repository из названия переменных

2023-10-17 14:14 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Set<Comment> comments;
Как?

2023-10-17 14:14 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Set<Comment> comments;
Как?

2023-10-24 09:31 UTC, Rolik8797 commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    List<Item> findAllByNameOrDescriptionContainingIgnoreCaseAndAvailableTrue(Pageable pageable,
Теперь "OR" имеет более высокий приоритет

2023-10-24 09:49 UTC, Rolik8797 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    private final ItemRepository items;
поправила

2023-10-24 10:06 UTC, Rolik8797 commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Set<Comment> comments;
поправила

2023-10-24 10:10 UTC, Rolik8797 commented
ТЗ 15-3

2023-10-24 16:50 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Set<Comment> comments;
Поля  comments и bookings отсюда нужно удалить, они создают проблему N+1 запроса

2023-10-24 16:50 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            List<Booking> itemBookings = item.getBookings();
Бронирования и комментарии нужно выгрузить для всего списка item-ов сразу и в цикле по item-ам распределить их для каждого item-а. Идти в репозиторий за бронированиями и комментариями не нужно

2023-10-24 16:50 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Set<Comment> comments;
Не исправлено, поля нужно удалить

2023-10-24 16:51 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +    @OneToMany(mappedBy = "request", fetch = FetchType.EAGER, cascade = CascadeType.ALL)
Не исправлено, этого поля здесь не должно быть. Проблема N+1 запроса

2023-10-26 13:56 UTC, Rolik8797 commented
ТЗ15-4

2023-10-27 11:36 UTC, NikolaiDem approved these changes

2023-10-29 14:20 UTC, merged